sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk8

cache:
  directories:
  - "$HOME/.m2"

script:
  - mvn clean package -U
  - docker build -t aljazb/dostavca-payment-calculator:latest .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push aljazb/dostavca-payment-calculator:latestBlake:dostavca-payment-calculator
